### ISSUE TITLE
Conflict with deployer on pimple/pimple version

### ISSUE THREAD

**Issue by leonexcc** [contao-community-alliance/event-dispatcher#10]
## Checklist before I submit this issue report

I confirm that:
- [x] I have tested this with the latest version available
- [x] I have checked the Contao community forums for references https://community.contao.org/
- [x] I have checked existing issues for duplicates and found none @ https://github.com/contao-community-alliance/event-dispatcher/issues?q=is%3Aissue

## My environment is:

(Please fill in the actual values from your environment)

| Key                                 | Value    | Comments                         |
| ----------------------------------- | ---------| ---------------------------------|
| PHP version:                        |  7.2.29        |                                  |
| Contao version:                     |  4.9.2        |                                  |

## Issue description

The required version of contao-community-alliance/dependency-container requires pimple in version 1.x and deployer requires pimple in version 3.x. This results in a conflict while installing with composer.

## Steps to reproduce

1. `composer require contao/core-bundle contao-community-alliance/event-dispatcher`
2. `composer require --dev deployer/deployer`

## Describe the behaviour of the application

Composer fails with `Your requirements could not be resolved to an installable set of packages.`

## Describe the expected behaviour of the application

I use menatwork/contao-multicolumnwizard-bundle (which uses contao-community-alliance/event-dispatcher) and deployer/deployer in my configurations and can't install this anymore at the moment.

As far as i understand the current code, the old dependency container is only used via the src/Resources/contao/config/services.php. But that file is only loaded in an environment with contao-community-alliance/dependency-container already installed.

Couldn't you make the requirement of contao-community-alliance/dependency-container and by that the requirement of pimple 1.x optional? Especial since the current version of event-dispatcher requires at least Contao 4.4.

## Screenshots

```
composer require --dev deployer/deployer
Using version ^6.7 for deployer/deployer
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Conclusion: don't install deployer/deployer v6.7.3
    - Conclusion: don't install deployer/deployer v6.7.2
    - Conclusion: don't install deployer/deployer v6.7.1
    - Conclusion: remove pimple/pimple v1.1.1
    - Installation request for deployer/deployer ^6.7 -> satisfiable by deployer/deployer[v6.7.0, v6.7.1, v6.7.2, v6.7.3].
    - Conclusion: don't install pimple/pimple v1.1.1
    - deployer/deployer v6.7.0 requires pimple/pimple ~3.0 -> satisfiable by pimple/pimple[v3.0.0, v3.0.1, v3.0.2, v3.1.0, v3.2.0, v3.2.1, v3.2.2, v3.2.3, v3.3.0].
    - Can only install one of: pimple/pimple[v3.0.0, v1.1.1].
    - Can only install one of: pimple/pimple[v3.0.1, v1.1.1].
    - Can only install one of: pimple/pimple[v3.0.2, v1.1.1].
    - Can only install one of: pimple/pimple[v3.1.0, v1.1.1].
    - Can only install one of: pimple/pimple[v3.2.0, v1.1.1].
    - Can only install one of: pimple/pimple[v3.2.1, v1.1.1].
    - Can only install one of: pimple/pimple[v3.2.2, v1.1.1].
    - Can only install one of: pimple/pimple[v3.2.3, v1.1.1].
    - Can only install one of: pimple/pimple[v3.3.0, v1.1.1].
    - Installation request for pimple/pimple (locked at v1.1.1) -> satisfiable by pimple/pimple[v1.1.1].


Installation failed, reverting ./composer.json to its original content.
```

**Comment by zonky2** [comment]
see https://github.com/contao-community-alliance/dependency-container/issues/20

@leonexcc is this still up to date or can it be closed?
