### ISSUE TITLE
Eigene Event Dispatcher Implementierung

### ISSUE THREAD

**Issue by tristanlins** [contao-community-alliance/event-dispatcher#4]
Wir sollten darüber nachdenken, eine eigene Event Dispatcher Implementierung (oder Fork) mit einigen Zusatzfunktionen zu entwickeln.

**Comment by discordier** [comment]
Gute Ideen, aber wir haben den propagator weggeschmissen (performance Gruende) und verwenden in Contao 4 den stock symfony dispatcher, ich mache daher nun mit will not fix zu.
