### ISSUE TITLE
Configure services as subscribers which depend on the event dispatcher

### ISSUE THREAD

**Issue by dmolineus** [contao-community-alliance/event-dispatcher#5]
This is rather a question than a bug report. But maybe there can be a generic solution, so I post it here.

What is the recommend way to register services as event subscribers which themselves require the event dispatcher as dependency?

Using the `event_subscribers.php` won't work, it will be called before the event dispatcher is assigned to the container. So it ends in an recursive loop.

I use the `initializeDependencyContainer` hook so far. But maybe there's a better solution. 

``` php
// services.php
$GLOBALS['container']['my.service'] = $container->share(
    function ($container) {
       return new My\Service($container['event-dispatcher']);
    }
);

// config.php
$GLOBALS['TL_HOOKS']['initializeDependencyContainer'][] = function($container) {
    /** @var \Symfony\Component\EventDispatcher\EventDispatcherInterface $eventDispatcher */
    $eventDispatcher = $container['event-dispatcher'];

    $eventDispatcher->addSubscriber($GLOBALS['container']['my.service']);
};
```

Maybe it could be the default way to trigger `$initializer->configure()` using this hook. So it would be avoided that unresolvable recursive dependencies to the event dispatcher exists.

**Comment by baumannsven** [comment]
#8

**Comment by baumannsven** [comment]
[WIP] Release/2.0.0#8

**Comment by discordier** [comment]
I guess we can close this now, as we are using symfony directly and have obsoleted this package?
What do you think @dmolineus?

**Comment by dmolineus** [comment]
Yes, there's no reason to still fix/improve it.
