### ISSUE TITLE
cannot git add files inside system/modules/symphony-event-dispatcher

### ISSUE THREAD

**Issue by rocchidavide** [contao-community-alliance/event-dispatcher#6]
Why files inside system/modules/symphony-event-dispatcher/ and system/modules/symphony-expression-language/ cannot be added to git?

**Comment by rocchidavide** [comment]
Files inside these folders aren't listed in git untracked files..

**Comment by discordier** [comment]
I can not follow your issue but it seems to have something to do with the `.gitignore` file of your Contao installation.

Certainly nothing our package will be able to fix. Closing therefore.
