### ISSUE TITLE
Contao 4 support

### ISSUE THREAD

**Issue by dmolineus** [contao-community-alliance/event-dispatcher#7]
I'd like to get our cca tools Contao 4 ready in the next months. I would work on it. But let's clarify the decisions which has to be made.

The main question is if we should continue using our own instance of the event dispatcher in Contao 4 or use symfonys default event dispatcher. I vote for using symfonys event dispatcher. We should get rid of cca/event-dispatcher in the future (Contao 5) anyway.

This could be easily implemented by providing different event dispatcher factories for different Contao versions.

Furthermore I'd like to get rid of the `CreateEventDispatcherEvent` event. When using the symfony event dispatcher in Contao 4 we can't switch to another event dispatcher anyway. Supporting the event also requires us to call the configurator in the service definition. I'd rather move the configurator to the `initializeDependencyContainer` hook. So that other services can have the event dispatcher as dependency.

What do you think @discordier @stefanheimes?

**Comment by discordier** [comment]
I was thinking about Contao 4 support also in the past and have made some experiments.

Now on your statements:

> The main question is if we should continue using our own instance of the event dispatcher in Contao 4 or use symfonys default event dispatcher.

Symfony dispatcher from the container - definitely!

> This could be easily implemented by providing different event dispatcher factories for different Contao versions.

Agreed - in Contao 4 it should get delegated.

> Furthermore I'd like to get rid of the `CreateEventDispatcherEvent` event.

Agreed - but we need to deprecate it first. So I suggest we publish a new major version where this is removed and an new patch level in current major where this triggers a deprecation notice.

> I'd rather move the configurator to the initializeDependencyContainer hook.

I'd rather build a container service for this which is triggered on system startup.

**Comment by stefanheimes** [comment]
Sounds good for me.

**Comment by discordier** [comment]
What do you guys think on #8?
Shall we move the discussion over there?

**Comment by discordier** [comment]
Feature branch has been merged and support branch `support/1.3.x` has been added.
We now need to release `1.3.1` (or better `1.4.0`?) which will trigger the deprecation notice.
